name: "publish"

on:
  release:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2.1.1
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12
        registry-url: https://registry.npmjs.org
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}

    
